name: Compile

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checknout most recent commit
        uses: actions/checkout@v3
        
      - name: Install valgrind
        run: sudo apt install valgrind

      - name: Compile "${{ inputs.path }}"
        run: find ${{ inputs.path }} -name "*.cpp" -exec g++ -std=c++17 -Wall -pedantic -pthread {} +

      - name: Valgrind check
        run: valgrind --leak-check=full --error-exitcode=1 ./a.out
