name: Pull Request checks

on:
  pull_request:
    branches: master

jobs:
  collect-design-patterns:
    runs-on: ubuntu-latest

    outputs:
      design-patterns-list: ${{ steps.set-list.outputs.list }}

    steps:
      - name: Checknout most recent commit
        uses: actions/checkout@v3

      - name: Set matrix with list of design patterns
        id: set-list
        run: |
          list="[$(ls -m -Q -d */)]"
          echo "::set-output name=list::$list"

  compile-all:
    needs: collect-design-patterns

    strategy:
      matrix:
        design-patterns: ${{ needs.collect-design-patterns.outputs.design-patterns-list }}

    uses: safar-jn/design-patterns/.github/workflows/compile.yml@master
    with:
      path: ${{ matrix.design-patterns }}
